# Generated by Django 4.1 on 2022-10-17 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage_services', '0002_alter_carmodel_options_alter_imagedesing_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagedesing',
            name='carmodel',
            field=models.ManyToManyField(blank=True, to='garage_services.carmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='imagedesing',
            name='vehicle',
            field=models.ManyToManyField(blank=True, to='garage_services.vehicle', verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image_model',
            field=models.ImageField(upload_to='image/services/%Y/%m/%d/', verbose_name='Изображение модели'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_model',
            field=models.ImageField(upload_to='image/services/%Y/%m/%d/', verbose_name='Изображение кузова'),
        ),
    ]
