# Generated by Django 4.1 on 2022-09-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=80, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('meta_robots', models.CharField(blank=True, max_length=50, null=True)),
                ('h1', models.CharField(blank=True, max_length=255, null=True)),
                ('tile', models.CharField(max_length=255, verbose_name='Тайтл Записи')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Контент Записи')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовать?')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('in_menu', models.BooleanField(default=True, verbose_name='Добавляем в меню?')),
                ('order', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название тега')),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='ArticleGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/blog/%Y/%m/%d/', verbose_name='Изображение записи')),
                ('mai_image', models.BooleanField(default=False, verbose_name='Главное фото?')),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_images', to='blog.article', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Изображение записи',
                'verbose_name_plural': 'Изображения записи',
            },
        ),
    ]
