# Generated by Django 4.1 on 2022-09-28 10:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('garage_services', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='carmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carmodel_articles', to='garage_services.carmodel', verbose_name='Модель'),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(to='blog.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='article',
            name='service',
            field=mptt.fields.TreeManyToManyField(blank=True, to='garage_services.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='article',
            name='service_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicevehicle_articles', to='garage_services.servicesvehicle', verbose_name='Кузов'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='article',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_articles', to='garage_services.vehicle', verbose_name='Кузов'),
        ),
    ]
