# Generated by Django 4.1 on 2022-09-28 10:06

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название на английском')),
                ('logo', models.ImageField(upload_to='image/logo/%Y/%m/%d/', verbose_name='Логотип марки')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_normochas', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Стоимость нормочаса')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Марка',
                'verbose_name_plural': 'Марки',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название на английском')),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название на русском')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('image_model', models.ImageField(upload_to='image/services/%Y/%m/%d/', verbose_name='Логотип концерна')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_carmodels', to='garage_services.brand', verbose_name='Марка')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название на русском')),
                ('name_en', models.CharField(max_length=255, verbose_name='Название на английском')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='image/logo/%Y/%m/%d/', verbose_name='Логотип концерна')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Концерн',
                'verbose_name_plural': 'Концерны',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('phone', models.IntegerField(verbose_name='Номер телефона')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Страница с которой пришла заявка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=80, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('meta_robots', models.CharField(blank=True, max_length=50, null=True)),
                ('h1', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название Услуги')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('in_menu', models.BooleanField(default=True, verbose_name='Добавляем ли в меню?')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('content', models.TextField(blank=True)),
                ('icon', models.ImageField(blank=True, upload_to='images/category/%Y/%m/%d/', verbose_name='Иконка категории')),
                ('min_normochas', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Минимально нормочасов')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='child_category', to='garage_services.service', verbose_name='Родительская услуга')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_year', models.IntegerField(verbose_name='Год начала производства')),
                ('stop_year', models.IntegerField(blank=True, null=True, verbose_name='Год прекращения производства')),
                ('image_model', models.ImageField(upload_to='image/services/%Y/%m/%d/', verbose_name='Логотип концерна')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('carmodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carmodel_vehicles', to='garage_services.carmodel', verbose_name='Модель')),
                ('services', mptt.fields.TreeManyToManyField(to='garage_services.service', verbose_name='Услуги')),
            ],
            options={
                'verbose_name': 'Кузов',
                'verbose_name_plural': 'Кузова',
            },
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('type', models.CharField(choices=[('MANUAL', 'МКПП'), ('AVTOMAT', 'АКПП'), ('ROBOT', 'Робот'), ('VARIATOR', 'Вариатор')], max_length=255, verbose_name='Тип КПП')),
                ('vendor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Производитель')),
                ('vehicle', models.ManyToManyField(blank=True, related_name='vehicle_transmissions', to='garage_services.vehicle', verbose_name='Кузов')),
            ],
            options={
                'verbose_name': 'Коробка передач',
                'verbose_name_plural': 'Коробки передач',
            },
        ),
        migrations.CreateModel(
            name='ServicesVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, max_length=80, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=255, null=True)),
                ('canonical_url', models.URLField(blank=True, null=True)),
                ('meta_robots', models.CharField(blank=True, max_length=50, null=True)),
                ('h1', models.CharField(blank=True, max_length=255, null=True)),
                ('min_normochas', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Минимально нормочасов')),
                ('normochas', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True, verbose_name='Нормочасов')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_vehicles', to='garage_services.service', verbose_name='Услуга')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_services', to='garage_services.vehicle', verbose_name='Кузов')),
            ],
            options={
                'verbose_name': 'Точная услуга',
                'verbose_name_plural': 'Точные услуги',
            },
        ),
        migrations.CreateModel(
            name='ImageDesing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='image/desing/%Y/%m/%d/', verbose_name='Фото для дизайна')),
                ('position', models.CharField(choices=[('FIRST', 'Первый экран'), ('FORM_1', 'Форма заявки 1'), ('WHY_ARE_WE', 'Мочему мы'), ('FORM_QUESTIONS', 'Остались вопросы')], max_length=25, verbose_name='Место размещения')),
                ('brand', models.ManyToManyField(blank=True, to='garage_services.brand', verbose_name='Марка')),
                ('group', models.ManyToManyField(blank=True, to='garage_services.group', verbose_name='Концерн')),
            ],
            options={
                'verbose_name': 'Изображение для оформления',
                'verbose_name_plural': 'Изображения для оформления',
            },
        ),
        migrations.AddField(
            model_name='group',
            name='services',
            field=mptt.fields.TreeManyToManyField(to='garage_services.service', verbose_name='Улсуги'),
        ),
        migrations.AddField(
            model_name='group',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('fuel', models.CharField(choices=[('PETROL', 'Бензиновый'), ('DIESEL', 'Дизельный'), ('ELECTRIC', 'Электрический'), ('HYBRID', 'Гибридный')], max_length=255, verbose_name='Тип двигателя')),
                ('horse_power', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Лошадиных сил')),
                ('torque', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Лошадиных сил')),
                ('vehicle', models.ManyToManyField(blank=True, related_name='vehicle_engines', to='garage_services.vehicle', verbose_name='Кузов')),
            ],
            options={
                'verbose_name': 'Двигатель',
                'verbose_name_plural': 'Двигатели',
            },
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='Тип привода')),
                ('vehicle', models.ManyToManyField(blank=True, related_name='vehicle_drives', to='garage_services.vehicle', verbose_name='Кузов')),
            ],
            options={
                'verbose_name': 'Тип привода',
                'verbose_name_plural': 'Типы привода',
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='services',
            field=mptt.fields.TreeManyToManyField(to='garage_services.service', verbose_name='Услуги'),
        ),
        migrations.AddField(
            model_name='brand',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_brands', to='garage_services.group', verbose_name='Концерн'),
        ),
        migrations.AddField(
            model_name='brand',
            name='services',
            field=mptt.fields.TreeManyToManyField(to='garage_services.service', verbose_name='Улсуги'),
        ),
        migrations.AddField(
            model_name='brand',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
