# Generated by Django 4.1 on 2022-10-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0004_alter_contact_phone_alter_review_service_vehicle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='about',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='О сотруднике'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
